 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_management_system;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
//import dao.connectionprovider;
import dao.connectionprovider;
import java.sql.*;
import javax.swing.ImageIcon;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Naveen
 */
public class addcustomer extends javax.swing.JFrame {
    public int checkname = 0;
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobileNumberPattern = "^[0-9]*$";
    public int sellmedicine = 0;
    public String temp = "";

    /**
     * Creates new form addcustomer
     */
    public addcustomer() {
        initComponents();
        //sellmedicine = 0;
        //temp = "";
    }
    public addcustomer(String mbno) {
        initComponents();
        temp = mbno;
        sellmedicine =1;
        mobilenobox.setText(temp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mobilenobox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailbox = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("ADD CUSTOMER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 91, 221, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 243, 78, -1));

        namebox.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        namebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameboxKeyReleased(evt);
            }
        });
        getContentPane().add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 312, 250, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("MOBILE NO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 243, 151, -1));

        mobilenobox.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        mobilenobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenoboxActionPerformed(evt);
            }
        });
        getContentPane().add(mobilenobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 312, 250, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("ADDRESS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 452, 250, -1));

        addressbox.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        addressbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressboxActionPerformed(evt);
            }
        });
        getContentPane().add(addressbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 509, 250, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("e-MAIL");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 452, 152, -1));

        emailbox.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(emailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1117, 509, 250, -1));

        backbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 60, -1, -1));

        savebtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        savebtn.setText("SAVE");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 670, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LIGHTBLUE.jpg"))); // NOI18N
        jLabel7.setText("..");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mobilenoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenoboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenoboxActionPerformed

    private void addressboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressboxActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        /*if(sellmedicine == 1){
            mobilenobox.setText(temp);
            System.out.println(temp);
            System.out.println(sellmedicine);
        }*/
        System.out.println(temp);
            System.out.println(sellmedicine);
        String name = namebox.getText();
        String mobileno = mobilenobox.getText();
        String email = emailbox.getText();
        String address = addressbox.getText();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Name field is required");
            
        }else if(mobileno.equals("")){
            JOptionPane.showMessageDialog(null,"Mobile number field is required");
        }else if(!mobileno.matches(mobileNumberPattern )|| mobileno.length() != 10){
            JOptionPane.showMessageDialog(null,"MobileNumber field is invalid");
        }else if(email.equals("")){
            JOptionPane.showMessageDialog(null,"e-Mail field is required");
        }else if(!email.matches(emailPattern)){
            JOptionPane.showMessageDialog(null,"Email field is invalid");
        }else if(address.equals("")){
            JOptionPane.showMessageDialog(null,"address field is required");
        }else{
        try{
            Connection con = connectionprovider.getcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from customer where name = '"+name+"'and mobile_no = '"+mobileno+"'");
            while(rs.next()){
                checkname = 1;
                JOptionPane.showMessageDialog(null,"Customer already exists");     
            }
            if(checkname == 0){
                PreparedStatement ps = con.prepareStatement("insert into customer(name,mobile_no,email,address) values(?,?,?,?)");
                ps.setString(1, name);
                ps.setString(2, mobileno);
                ps.setString(3, email);
                ps.setString(4, address);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"User added Successfully.");
                setVisible(false);
                System.out.println(sellmedicine+"before break");
                if(sellmedicine == 1){
                    setVisible(false);
                    //break;
                    System.out.println("inside sellmedicine");
                }
                else
                    new addcustomer().setVisible(true);
                System.out.println("outside sellmedicine");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        }
        
    }//GEN-LAST:event_savebtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new customercolumn().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void nameboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameboxKeyReleased
        // TODO add your handling code here:
    
    }//GEN-LAST:event_nameboxKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addcustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addcustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressbox;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField emailbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mobilenobox;
    private javax.swing.JTextField namebox;
    private javax.swing.JButton savebtn;
    // End of variables declaration//GEN-END:variables
}
