/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_management_system;
import java.sql.Connection;
import java.sql.PreparedStatement;
//import dao.connectionprovider;
import dao.connectionprovider;
import java.sql.*;
import javax.swing.ImageIcon;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Naveen
 */
public class addemployee extends javax.swing.JFrame {
    public int checkUsername = 0;
    public String emailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String mobileNumberPattern = "^[0-9]*$";
    //private Object dFormat;

    /**
     * Creates new form add employee
     */
    public addemployee() {
        initComponents();
        iconlabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        addemp = new javax.swing.JLabel();
        rolebox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        namelable = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        dateofbirth = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        phoneno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        user_namebox = new javax.swing.JLabel();
        emailtxtbox = new javax.swing.JTextField();
        usernametxtbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passwordbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addressbox = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        iconlabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addemp.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        addemp.setText("Add Employee");
        getContentPane().add(addemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 81, 167, -1));

        rolebox.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        rolebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Pharmacist", "" }));
        getContentPane().add(rolebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 254, 310, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("User Role");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 198, 320, 30));

        namelable.setBackground(new java.awt.Color(0, 0, 0));
        namelable.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        namelable.setText("Name");
        getContentPane().add(namelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 330, 320, -1));

        namebox.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameboxActionPerformed(evt);
            }
        });
        getContentPane().add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 372, 320, -1));
        getContentPane().add(dateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 482, 320, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("DOB Date Of Birth");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 443, 320, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Mobile number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 320, -1));

        phoneno.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoActionPerformed(evt);
            }
        });
        getContentPane().add(phoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, 320, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("e-Mail");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 200, 199, 32));

        user_namebox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        user_namebox.setText("User Name");
        getContentPane().add(user_namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 330, 199, -1));

        emailtxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtboxActionPerformed(evt);
            }
        });
        getContentPane().add(emailtxtbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 241, 280, -1));

        usernametxtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametxtboxActionPerformed(evt);
            }
        });
        usernametxtbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernametxtboxKeyReleased(evt);
            }
        });
        getContentPane().add(usernametxtbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 370, 290, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 440, 137, -1));

        passwordbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordboxActionPerformed(evt);
            }
        });
        getContentPane().add(passwordbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 490, 290, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 560, 153, -1));
        getContentPane().add(addressbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 610, 280, -1));

        savebtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        savebtn.setText("save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 710, -1, -1));

        backbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        backbtn.setText("back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 60, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        iconlabel.setText("..");
        getContentPane().add(iconlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 370, 30, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1111.jpg"))); // NOI18N
        jLabel8.setText("..");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-380, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameboxActionPerformed

    private void phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenoActionPerformed

    private void passwordboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordboxActionPerformed

    private void emailtxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtboxActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        String userrole;
        userrole = (String) rolebox.getSelectedItem();
        String name = namebox.getText();
        //SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        //Date date = dateofbirth.getDate();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = dateofbirth.getDate();

        String dob = "";
        if(date != null ){
            System.out.println("qwerty");
            dob = dFormat.format(dateofbirth.getDate());
        }
        String mobilenumber=phoneno.getText();
        String email=emailtxtbox.getText();
        String password=passwordbox.getText();
        String username=usernametxtbox.getText();
        String address=addressbox.getText();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Name field is required");
        }else if(mobilenumber.equals("")){
            JOptionPane.showMessageDialog(null,"Mobile number field is required");
        }else if(!mobilenumber.matches(mobileNumberPattern )|| mobilenumber.length() != 10){
            JOptionPane.showMessageDialog(null,"MobileNumber field is invalid");
        }else if(email.equals("")){
            JOptionPane.showMessageDialog(null,"e-Mail field is required");
        }else if(!email.matches(emailPattern)){
            JOptionPane.showMessageDialog(null,"Email field is invalid");
        }else if(password.equals("")){
            JOptionPane.showMessageDialog(null,"password field is required");
        }else if(address.equals("")){
            JOptionPane.showMessageDialog(null,"address field is required");
        }else if(date.equals("")){
            JOptionPane.showMessageDialog(null,"date field is required");
        }else if(username.equals("")){
            JOptionPane.showMessageDialog(null,"username field is required");
        }else if(checkUsername==1){
            JOptionPane.showMessageDialog(null,"Usrname already Exist");
        }else{
            try{
            Connection con = connectionprovider.getcon();
                PreparedStatement ps = con.prepareStatement("insert into app_user(userRole,name,dob,mobile_no,email,user_name,password,address,status) values(?,?,?,?,?,?,?,?,'Active')");
                ps.setString(1, userrole);
                ps.setString(2, name);
                ps.setString(3, dob);
                ps.setString(4, mobilenumber);
                ps.setString(5, email);
                ps.setString(6, username);
                ps.setString(7, password);
                ps.setString(8, address);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"User added Successfully.");
                setVisible(false);
                new addemployee().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        }

    }//GEN-LAST:event_savebtnActionPerformed

    private void usernametxtboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernametxtboxKeyReleased
        // TODO add your handling code here:
        /* String username = usernametxtbox.getText();
        if (! username.equals("")){
            iconlabel.setVisible(true);
            iconlabel.setIcon(new ImageIcon("E:\\EDUCATION\\4th semester\\sem 4 mini\\code editors\\NetBeans-24\\projects\\pharmachy john saro\\pharmacy_management_system\\src\\icons\\yes.png"));
            iconlabel.setText("");
            checkusername = 0;
            
            try{
             
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy?useSSL=false","root","naveen@2992005"); 
                Connection con = connectionprovider.getcon();
                java.sql.Statement st = con.createStatement();
                ResultSet rs;
                rs = st.executeQuery("SELECT * from app_user where name = '"+username+"'");
                //Connection con = connectionprovider.getcon();
                ResultSet rs;
                Statement st = con.createStatement();
                rs = st.executeQuery("SELECT * from app_user where name = '"+username+"'");
                System.out.println("summa1");
                while(rs.next()){
                    checkusername = 1;
                    iconlabel.setIcon(new ImageIcon("E:\\EDUCATION\\4th semester\\sem 4 mini\\code editors\\NetBeans-24\\projects\\pharmachy john saro\\pharmacy_management_system\\src\\icons\\no.png"));
                    iconlabel.setText("");
                }
                }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        else{ 
            iconlabel.setVisible(false);
        }*/
        String username = usernametxtbox.getText();  
    if(!username.equals("")){
        iconlabel.setVisible(true);
        iconlabel.setIcon(new ImageIcon("src\\icons\\yes.png"));
        iconlabel.setText("");
        checkUsername = 0;
        
        try{
            //Connection con = connectionprovider.getcon();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy?useSSL=false","root","naveen@2992005");  
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from app_user where user_name = '"+username+"'");
            while(rs.next()){
                checkUsername = 1;
                iconlabel.setIcon(new ImageIcon("src\\icons\\close.png"));
                iconlabel.setText("");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
    }
    else{
        iconlabel.setVisible(false);
    }


    }//GEN-LAST:event_usernametxtboxKeyReleased

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new OwnerDashboard().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void usernametxtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametxtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametxtboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addemp;
    private javax.swing.JTextField addressbox;
    private javax.swing.JButton backbtn;
    private com.toedter.calendar.JDateChooser dateofbirth;
    private javax.swing.JTextField emailtxtbox;
    private javax.swing.JLabel iconlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField namebox;
    private javax.swing.JLabel namelable;
    private javax.swing.JTextField passwordbox;
    private javax.swing.JTextField phoneno;
    private javax.swing.JComboBox<String> rolebox;
    private javax.swing.JButton savebtn;
    private javax.swing.JLabel user_namebox;
    private javax.swing.JTextField usernametxtbox;
    // End of variables declaration//GEN-END:variables
}
