/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_management_system;

import javax.swing.JOptionPane;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
//import dao.connectionprovider;
import dao.connectionprovider;
import static java.lang.Integer.parseInt;
import java.sql.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Naveen
 */
public class addmedicine extends javax.swing.JFrame {
    public String NumberPattern = "^[0-9]*$";
public int checkname = 0;

    /**
     * Creates new form addmedicine
     */
    public addmedicine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        medidbox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        companynamebox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        quantitybox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        unitpricebox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Add Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 79, 233, -1));

        backbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 50, -1, -1));

        exitbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Medicine ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 252, 275, -1));

        medidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medidboxActionPerformed(evt);
            }
        });
        getContentPane().add(medidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 294, 275, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Name");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 362, 275, -1));
        getContentPane().add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 404, 275, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Company Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 471, 275, -1));

        companynamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companynameboxActionPerformed(evt);
            }
        });
        getContentPane().add(companynamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 513, 275, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 252, 245, -1));
        getContentPane().add(quantitybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 294, 275, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("Price Per Unit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 362, 275, -1));
        getContentPane().add(unitpricebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 404, 275, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/savecolor.png"))); // NOI18N
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(992, 496, 185, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ORANGE_TABLET.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void companynameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companynameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companynameboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = namebox.getText();
        String id = medidbox.getText();
        String unitprice = unitpricebox.getText();
        String quantity = quantitybox.getText();
        String companyname = companynamebox.getText();
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Name field is required");
        }else if(id.equals("")){
            JOptionPane.showMessageDialog(null,"medicine ID field is required");
        }else if(companyname.equals("")){
            JOptionPane.showMessageDialog(null,"company name field is required");
        }else if(quantity.equals("")){
            JOptionPane.showMessageDialog(null,"Quantity field is required");
        }else if(unitprice.equals("")){
            JOptionPane.showMessageDialog(null,"price per unit ID field is required");
        }else if(!unitprice.matches(NumberPattern )){
            JOptionPane.showMessageDialog(null,"price per unit field is invalid");
        }else if(!quantity.matches(NumberPattern )){
            JOptionPane.showMessageDialog(null,"Quantity field is invalid");
        }else{
            try{
            Connection con = connectionprovider.getcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from medicines where medname = '"+name+"'or unique_id= '"+id+"'");
            while(rs.next()){
                checkname = 1;
                JOptionPane.showMessageDialog(null,"medicine Id already exists");     
            }
            if(checkname == 0){
                PreparedStatement ps = con.prepareStatement("insert into medicines (medname,unique_id,companyname,quantity,amount) values(?,?,?,?,?)");
                ps.setString(1, name);
                ps.setString(2, id);
                ps.setString(3,companyname );
                int q=parseInt(quantity);
                ps.setInt(4,q);
                int amt=parseInt(unitprice);
                ps.setInt(5,amt);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Medicine added Successfully.");
                setVisible(false);
                new addmedicine().setVisible(true);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void medidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medidboxActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new medicines().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"do you want to exit","select",JOptionPane.YES_NO_OPTION);
        if(a == 0 ){
            System.exit(0);
        }
    }//GEN-LAST:event_exitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addmedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addmedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addmedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addmedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addmedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField companynamebox;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField medidbox;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField quantitybox;
    private javax.swing.JTextField unitpricebox;
    // End of variables declaration//GEN-END:variables
}
