/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_management_system;

import javax.swing.JOptionPane;

/**
 *
 * @author Naveen
 */
public class medicines extends javax.swing.JFrame {
    private String rol = "";
    private String nam = "";

    /**
     * Creates new form medicines
     */
    public medicines() {
        initComponents();
    }
    public medicines(String role) {
        rol = role;
        initComponents();
    }
    public medicines(String role,String name) {
        rol = role;
        nam = name;
        initComponents();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addmedicinebtn = new javax.swing.JButton();
        sellmedicinebtn = new javax.swing.JButton();
        updatemedicinebtn = new javax.swing.JButton();
        viewbillbtn = new javax.swing.JButton();
        viemdicinebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("MEDICINE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 71, 213, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        jButton1.setText("BACK");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2145, 94, -1, -1));

        addmedicinebtn.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        addmedicinebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addmed.jpg"))); // NOI18N
        addmedicinebtn.setText("ADD MEDICINE");
        addmedicinebtn.setPreferredSize(new java.awt.Dimension(200, 50));
        addmedicinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmedicinebtnActionPerformed(evt);
            }
        });
        getContentPane().add(addmedicinebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 226, 240, 70));

        sellmedicinebtn.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        sellmedicinebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sell med.png"))); // NOI18N
        sellmedicinebtn.setText("SELL MEDICINE");
        sellmedicinebtn.setPreferredSize(new java.awt.Dimension(200, 50));
        sellmedicinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellmedicinebtnActionPerformed(evt);
            }
        });
        getContentPane().add(sellmedicinebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 240, 70));

        updatemedicinebtn.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        updatemedicinebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update med.png"))); // NOI18N
        updatemedicinebtn.setText("UPDATE MEDICINE");
        updatemedicinebtn.setPreferredSize(new java.awt.Dimension(200, 50));
        updatemedicinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatemedicinebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatemedicinebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 240, 70));

        viewbillbtn.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        viewbillbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1bill.png"))); // NOI18N
        viewbillbtn.setText("VIEW BILL");
        viewbillbtn.setPreferredSize(new java.awt.Dimension(200, 50));
        viewbillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbillbtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewbillbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 510, 260, 70));

        viemdicinebtn.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        viemdicinebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/listmed 2.jpg"))); // NOI18N
        viemdicinebtn.setText("VIEW MEDICINE");
        viemdicinebtn.setPreferredSize(new java.awt.Dimension(200, 50));
        viemdicinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viemdicinebtnActionPerformed(evt);
            }
        });
        getContentPane().add(viemdicinebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1228, 226, 240, 70));

        backbtn.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 80, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ORANGE_TABLET.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viemdicinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viemdicinebtnActionPerformed
        // TODO add your handling code here
        setVisible(false);
            new viewmedicine().setVisible(true);
        
    }//GEN-LAST:event_viemdicinebtnActionPerformed

    private void viewbillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbillbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new viewbill().setVisible(true);
    }//GEN-LAST:event_viewbillbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        //setVisible(false);
        System.out.println("qwerty");
        if(rol.equals("admin")){
        new OwnerDashboard().setVisible(true);
        }else if (rol.equals("worker")){
           new workerboard().setVisible(true);
        }else{
            new OwnerDashboard().setVisible(true);
        }
    }//GEN-LAST:event_backbtnActionPerformed

    private void addmedicinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmedicinebtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new addmedicine().setVisible(true);
        
    }//GEN-LAST:event_addmedicinebtnActionPerformed

    private void updatemedicinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatemedicinebtnActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        System.out.println("qwerty");
        new updatemedicine().setVisible(true);
        
    }//GEN-LAST:event_updatemedicinebtnActionPerformed

    private void sellmedicinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellmedicinebtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new sellmedicine().setVisible(true);
    }//GEN-LAST:event_sellmedicinebtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"do you want to exit","select",JOptionPane.YES_NO_OPTION);
        if(a == 0 ){  //yes or no return yes =1 no=0
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medicines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addmedicinebtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton sellmedicinebtn;
    private javax.swing.JButton updatemedicinebtn;
    private javax.swing.JButton viemdicinebtn;
    private javax.swing.JButton viewbillbtn;
    // End of variables declaration//GEN-END:variables
}
