/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_management_system;

import javax.swing.JOptionPane;

/**
 *
 * @author Naveen
 */
public class OwnerDashboard extends javax.swing.JFrame {
    private String username ="";
    private String owner ="owner";

    /**
     * Creates new form OwnerDashboard
     */
    public OwnerDashboard() {
        initComponents();
    }
    
    public OwnerDashboard(String tempusername) {
        initComponents();
        username = tempusername;
        setLocationRelativeTo(null);
        System.out.println(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addempbtn = new javax.swing.JButton();
        medicinebtn = new javax.swing.JButton();
        addcustbtn = new javax.swing.JButton();
        updtempbtn = new javax.swing.JButton();
        viewprobtn = new javax.swing.JButton();
        viewbillbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1834, 1024));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addempbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add emp.png"))); // NOI18N
        addempbtn.setText("     ADD EMPLOYEE");
        addempbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addempbtnMouseClicked(evt);
            }
        });
        addempbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addempbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addempbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 272, 188, 62));

        medicinebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medicine 2.png"))); // NOI18N
        medicinebtn.setText("                MEDICINE");
        medicinebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicinebtnMouseClicked(evt);
            }
        });
        medicinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicinebtnActionPerformed(evt);
            }
        });
        getContentPane().add(medicinebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 272, 188, 62));

        addcustbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Users.png"))); // NOI18N
        addcustbtn.setText("           CUSTOMER ");
        addcustbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addcustbtnMouseClicked(evt);
            }
        });
        addcustbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcustbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addcustbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 272, 188, 62));

        updtempbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/updateemp.png"))); // NOI18N
        updtempbtn.setText("      UPDATE EMPLOYEE");
        updtempbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updtempbtnMouseClicked(evt);
            }
        });
        updtempbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtempbtnActionPerformed(evt);
            }
        });
        getContentPane().add(updtempbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(936, 272, -1, 62));

        viewprobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/id.png"))); // NOI18N
        viewprobtn.setText("          VIEW USERS");
        viewprobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewprobtnMouseClicked(evt);
            }
        });
        viewprobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewprobtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewprobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 431, 188, 62));

        viewbillbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1bill.png"))); // NOI18N
        viewbillbtn.setText("                  VIEW BILL");
        viewbillbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewbillbtnMouseClicked(evt);
            }
        });
        viewbillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbillbtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewbillbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 431, 188, 62));

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_1.png"))); // NOI18N
        logoutbtn.setText("                  LOGOUT");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 431, 188, 62));

        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit_1.png"))); // NOI18N
        exitbtn.setText("                 EXIT");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(936, 431, 220, 62));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 37, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMINISTRATOR   DASHBOARD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 132, 253, 43));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/DASHBOARD BACKGROUND_1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addempbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addempbtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addempbtnActionPerformed

    private void medicinebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicinebtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new medicines().setVisible(true);
    }//GEN-LAST:event_medicinebtnMouseClicked

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"do yo want to logout application","select",JOptionPane.YES_NO_OPTION);
        if(a == 0 ){
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"do you want to exit","select",JOptionPane.YES_NO_OPTION);
        if(a == 0 ){
            System.exit(0);
        }
    }//GEN-LAST:event_exitbtnActionPerformed

    private void viewprobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewprobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewprobtnActionPerformed

    private void updtempbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtempbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updtempbtnActionPerformed

    private void addempbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addempbtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new addemployee().setVisible(true);
        
    }//GEN-LAST:event_addempbtnMouseClicked

    private void addcustbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcustbtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new customercolumn().setVisible(true);
        
    }//GEN-LAST:event_addcustbtnMouseClicked

    private void updtempbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updtempbtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new updateemployee().setVisible(true);
    }//GEN-LAST:event_updtempbtnMouseClicked

    private void viewprobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewprobtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new viewuser().setVisible(true);
    }//GEN-LAST:event_viewprobtnMouseClicked

    private void viewbillbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbillbtnMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new viewbill(owner).setVisible(true);
    }//GEN-LAST:event_viewbillbtnMouseClicked

    private void medicinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicinebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicinebtnActionPerformed

    private void addcustbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcustbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addcustbtnActionPerformed

    private void viewbillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbillbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewbillbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OwnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OwnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OwnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new OwnerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcustbtn;
    private javax.swing.JButton addempbtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton medicinebtn;
    private javax.swing.JButton updtempbtn;
    private javax.swing.JButton viewbillbtn;
    private javax.swing.JButton viewprobtn;
    // End of variables declaration//GEN-END:variables
}
