/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_management_system;

import javax.swing.JOptionPane;
import java.sql.*;
import dao.connectionprovider;

/**
 *
 * @author Naveen
 */
public class profile extends javax.swing.JFrame {
    private String emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
    private String mobileNumberPattern = "^[0-9]{10}$";
    private String username = "";
    private String rol = "";

    /**
     * Creates new form profile
     */
    public profile() {
        initComponents();
    }
    public profile(String tempUsername,String role){
        initComponents();
        username = tempUsername;
        rol = role;
        setLocationRelativeTo(null);
        System.out.println("from profile"+username+rol);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mobilenobox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailbox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        passwordbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        usernamelable = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Profile");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 93, 149, -1));

        backbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 60, -1, -1));

        exitbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 206, 71, -1));

        namebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameboxActionPerformed(evt);
            }
        });
        getContentPane().add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 239, 298, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Mobile Number");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 415, 298, 22));
        getContentPane().add(mobilenobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 455, 298, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 519, 298, 22));

        addressbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressboxActionPerformed(evt);
            }
        });
        getContentPane().add(addressbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 553, 298, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("e-Mail");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 617, 298, 22));
        getContentPane().add(emailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 645, 298, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 303, 298, -1));
        getContentPane().add(passwordbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 336, 292, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/updateemp.png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 721, -1, -1));

        usernamelable.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        usernamelable.setText("User Name");
        getContentPane().add(usernamelable, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/profile.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, 140));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1111.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void addressboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressboxActionPerformed

    private void nameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameboxActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        if (rol.equals("worker")){
            new workerboard().setVisible(true);
        }else{
        new OwnerDashboard().setVisible(true);
        }
    }//GEN-LAST:event_backbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"do you want to exit","select",JOptionPane.YES_NO_OPTION);
        if(a == 0 ){  //yes or no return yes =1 no=0
            System.exit(0);
        }   
    }//GEN-LAST:event_exitbtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
             Connection con = connectionprovider.getcon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from app_user where user_name ='"+username+"'");
            while(rs.next()){
                namebox.setText(rs.getString("name"));
                mobilenobox.setText(rs.getString("mobile_no"));
                emailbox.setText(rs.getString("email"));
                passwordbox.setText(rs.getString("password"));

                emailbox.setText(rs.getString("email"));
                addressbox.setText(rs.getString("address"));
                usernamelable.setText(username);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = namebox.getText();
        String mobileNumber = mobilenobox.getText();
        String email = emailbox.getText();
        String address = addressbox.getText();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Name field is required.");
        } else if(mobileNumber.equals("")){
            JOptionPane.showMessageDialog(null,"Mobile Number field is required.");
        } else if(!mobileNumber.matches(mobileNumberPattern) || mobileNumber.length() !=10){
            JOptionPane.showMessageDialog(null,"Mobile Number field is invalid.");
        } else if(!email.matches(emailPattern)){
            JOptionPane.showMessageDialog(null,"Email field is invalid.");
        } else if(email.equals("")){
            JOptionPane.showMessageDialog(null,"Email field is required.");
        } else if(address.equals("")){
            JOptionPane.showMessageDialog(null,"Address field is required");
        } else{
            try{
                Connection con = connectionprovider.getcon();
                PreparedStatement ps = con.prepareStatement("update app_user set name=?,mobile_no=?,email=?,address=? where user_name=?");
                ps.setString(1, name);
                ps.setString(2, mobileNumber);
                ps.setString(3, email);
                ps.setString(4, address);
                ps.setString(5, username);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Profile Updated Successfully");
                setVisible(false);
                new profile(username,rol).setVisible(true);
            } catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressbox;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField emailbox;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mobilenobox;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField passwordbox;
    private javax.swing.JLabel usernamelable;
    // End of variables declaration//GEN-END:variables
}
