/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_management_system;
import java.sql.*;
import javax.mail.*;
import javax.mail.internet.*;
import java.util.Properties;
import javax.activation.*;
import java.util.*;
import java.util.Date;
import javax.mail.internet.MimeBodyPart;
//import javax.mail.internet.Multipart;
import dao.connectionprovider;
import dao.Open;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.mail.*;
/**
 *
 * @author Naveen
 */
public class sellmedicine extends javax.swing.JFrame {
     private String numptn = "^[0-9]*$";
    private double totprice=0.0;
    private String billid="";
    private String username="";
    public String uid = "";
    private String noofunit ="";
    private String price = "";
    private int checkUserExist = 0;
    public String custname = "";
    public String custemail = "";
    private int minvalue = 69;
    private String path = "C:\\Users\\Naveen\\OneDrive\\Documents\\mini project bills\\";
    

    /**
     * Creates new form sellmedicine
     */
    public sellmedicine() {
        initComponents();
    }
    public sellmedicine(String uname) {
        initComponents();
        username=uname;
    }
    
    public void medicinename(String nameoruniqueid){
                DefaultTableModel model =(DefaultTableModel) medicinetable.getModel();
                model.setRowCount(0);
                try{
                    Connection con = connectionprovider.getcon();
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery("SELECT * from medicines where medname like '"+nameoruniqueid+"%'or unique_id like '"+nameoruniqueid+"%'");
                    while(rs.next()){
                        model.addRow(new Object[]{rs.getString("unique_id")+"-"+rs.getString("medname")});
                    }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                }
    }

    public void clearmedfield(){
        medicinebox.setText("");
        namebox.setText("");
        companynamebox.setText("");
        custmobilenobox.setText("");
        unitpricebox.setText("");
        no_of_units_box.setText("");
        amtbox.setText("");
    }
    public String getuniqueid(String prefix ){
        return prefix + System.nanoTime();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        medicinebox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        companynamebox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        custmobilenobox = new javax.swing.JTextField();
        addcartbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        unitpricebox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        no_of_units_box = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        amtbox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        carttable = new javax.swing.JTable();
        finalamtlabel = new javax.swing.JLabel();
        printbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        medicinetable = new javax.swing.JTable();
        searchbox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("SELL MEDICINE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 14, 324, -1));

        backbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 20, -1, -1));

        exitbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Medicine ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 250, -1));

        medicinebox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(medicinebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 250, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 250, -1));

        namebox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 250, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Company Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 250, -1));

        companynamebox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(companynamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 250, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Customer Mobile No");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 178, -1));

        custmobilenobox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        custmobilenobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custmobilenoboxActionPerformed(evt);
            }
        });
        getContentPane().add(custmobilenobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 370, 285, -1));

        addcartbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        addcartbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add to cart.png"))); // NOI18N
        addcartbtn.setText("Add To Cart");
        addcartbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addcartbtnMouseClicked(evt);
            }
        });
        addcartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcartbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addcartbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("Price Per Unit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 100, 249, -1));

        unitpricebox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(unitpricebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 140, 249, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("No Of Units");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 180, 249, -1));

        no_of_units_box.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        no_of_units_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                no_of_units_boxKeyReleased(evt);
            }
        });
        getContentPane().add(no_of_units_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 210, 249, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setText("Amount");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 250, 249, -1));

        amtbox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(amtbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 280, 249, -1));

        carttable.setBackground(new java.awt.Color(255, 183, 109));
        carttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medice id", "Name", "comany Name", "Unit Price", "No Of Units", "total Price"
            }
        ));
        carttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(carttable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 420, 750, 290));

        finalamtlabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        finalamtlabel.setText("RS:");
        getContentPane().add(finalamtlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 740, 86, 42));

        printbtn.setBackground(new java.awt.Color(255, 176, 50));
        printbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        printbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sell med 2.jpg"))); // NOI18N
        printbtn.setText("Purchase & Print");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });
        getContentPane().add(printbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 730, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        jLabel9.setText("search");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 110, -1));

        medicinetable.setBackground(new java.awt.Color(255, 183, 109));
        medicinetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MEDICINES"
            }
        ));
        medicinetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medicinetableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(medicinetable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 540));

        searchbox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxKeyReleased(evt);
            }
        });
        getContentPane().add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 330, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ORANGE_TABLET.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custmobilenoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custmobilenoboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custmobilenoboxActionPerformed

    public  void sendEmail(String recipientEmail,String billno) {
    final String senderEmail = "naveenragavi5@gmail.com";
       final String senderPassword = "aasnsaozdqwedkzb";
       
       Properties props = new Properties();
props.put("mail.smtp.auth", "true");
props.put("mail.smtp.starttls.enable", "true"); // StartTLS on port 587
props.put("mail.smtp.ssl.protocols", "TLSv1.2");
props.put("mail.smtp.host", "smtp.gmail.com");
props.put("mail.smtp.port", "587"); // or 465 for SSL



        /*Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", "smtp.gmail.com");
        properties.put("mail.smtp.port", "587");*/
        //Properties props = new Properties();
        //props.put("mail.debug", "true");

        Session session = Session.getInstance(props, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(senderEmail, senderPassword);
            }
        });

        try {
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(senderEmail));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(recipientEmail));
            message.setSubject("Purchase from john saro medical");

            // Body Part (text)
            MimeBodyPart messageBodyPart = new MimeBodyPart();
            messageBodyPart.setText("Dear Sir,\n\n Below we have attached the bill of the purchase of items from our john saro medicals");

            // Attachment Part (PDF)
            MimeBodyPart attachmentPart = new MimeBodyPart();
            String filename = path+billno+".pdf";
            File file = new File(path+billno+".pdf");
            //JOptionPane.showMessageDialog(null,filename);
            
            if (file.exists()) {
                attachmentPart.attachFile(file);
                //JOptionPane.showMessageDialog(null,"file found");
                
            } else {
                System.out.println("Attachment file not found!");
                JOptionPane.showMessageDialog(null,"file not found");
            }

            // Create Multipart
            Multipart multipart = new MimeMultipart();
            multipart.addBodyPart(messageBodyPart);
            multipart.addBodyPart(attachmentPart);

            // Set content
            message.setContent(multipart);

            // Send Email
            Transport.send(message);
            System.out.println("Email with PDF sent successfully!");
            JOptionPane.showMessageDialog(null,"Email with PDF sent successfully!");

        } catch (Exception e) {
            e.printStackTrace();
        }
}
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        medicinename("");
        
    }//GEN-LAST:event_formComponentShown

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new medicines().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"do you want to exit","select",JOptionPane.YES_NO_OPTION);
        if(a == 0 ){  //yes or no return yes =1 no=0
            System.exit(0);
        }  
    }//GEN-LAST:event_exitbtnActionPerformed

    private void searchboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyReleased
        // TODO add your handling code here:
        String search=searchbox.getText();
        medicinename(search);
    }//GEN-LAST:event_searchboxKeyReleased

    private void medicinetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medicinetableMouseClicked
        // TODO add your handling code here:
        int index = medicinetable.getSelectedRow();
        TableModel model = medicinetable.getModel();
        String nameoruniqueid= model.getValueAt(index,0).toString();
        String uniqueid[] = nameoruniqueid.split("-",0);
        try{

            Connection con = connectionprovider.getcon();
            Statement st = con.createStatement();
            ResultSet rs;
            rs = st.executeQuery("SELECT * from medicines where unique_id = '"+uniqueid[0]+"'");
           while(rs.next()){
               //System.out.println(rs.next());
               medicinebox.setText(uniqueid[0]);
               namebox.setText(rs.getString("medname"));
               companynamebox.setText(rs.getString("companyname"));
               //custmobilenobox.setText("");
               unitpricebox.setText(rs.getString("amount"));
               no_of_units_box.setText("");
               amtbox.setText("");
           }
        }
        
        
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_medicinetableMouseClicked

    private void no_of_units_boxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_of_units_boxKeyReleased
        // TODO add your handling code here:
         noofunit = no_of_units_box.getText();
         price =unitpricebox.getText();
        if(!noofunit.matches(numptn) || noofunit.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Numbers for no. of Units");
            no_of_units_box.setText("");
        }
        int tot = Integer.parseInt(price) * Integer.parseInt(noofunit);
        amtbox.setText(String.valueOf(tot));
    }//GEN-LAST:event_no_of_units_boxKeyReleased

    private void addcartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcartbtnActionPerformed
String mobileno = custmobilenobox.getText();
        if(mobileno.equals("")){
            JOptionPane.showMessageDialog(null, "mobile number field required");
        } 
        else{
            if(checkUserExist == 0){
            try{
                Connection con = connectionprovider.getcon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from customer where mobile_no ='"+mobileno+"'");
                while(rs.next()){
                    checkUserExist = 1;
                    uid = rs.getString("cid_pk");
                    custname=rs.getString("name");
                    custemail = rs.getString("email");
                }
        }   catch(Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
            if(checkUserExist == 0){
                JOptionPane.showMessageDialog(null,"new customer \n Add the customer to database");
                //setVisible(false);
                new addcustomer(mobileno).setVisible(true);
               no_of_units_box.setText(noofunit);//TO RETAIN VALUE AGAIN AFTER GOING AND COMMING BACK TO YHIS PAGE
               int tot = Integer.parseInt(price) * Integer.parseInt(noofunit);
               amtbox.setText(String.valueOf(tot));
               //to get cid after adding customer;
               try{
                Connection con = connectionprovider.getcon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from customer where mobile_no ='"+mobileno+"'");
                while(rs.next())
                    uid = rs.getString("cid_pk");
               }catch(Exception e) {
                JOptionPane.showMessageDialog(null,e);
               }
               }
            }
        }
        noofunit = no_of_units_box.getText();
         System.out.println(noofunit);
         price =unitpricebox.getText();
         String id    = medicinebox.getText();
         String mname = namebox.getText();
         String cname = companynamebox.getText();
         String cnum  = custmobilenobox.getText();
         String amt   = amtbox.getText();
         int checkstock = 0;
         int incart = 0;
         try{
             Connection con = connectionprovider.getcon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from medicines where unique_id ='"+id+"'");
                while(rs.next()){
                    if(rs.getInt("quantity") >= Integer.parseInt(noofunit)){
                         System.out.println(rs.getInt("quantity"));
                        checkstock = 1;
                    }else{
                        JOptionPane.showMessageDialog(null,"Medicine Out Of Stock "+rs.getInt("quantity")+"Left ");
                    }
                  }
               }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e);
         }
         System.out.println(checkstock);
         if(checkstock == 1){
              DefaultTableModel crtmodel =(DefaultTableModel) carttable.getModel();
              if(carttable.getRowCount() != 0){
                  for(int i = 0 ; i < carttable.getRowCount();i++){
                      if(crtmodel.getValueAt(i,0).toString().equals(id)){
                      //if(Integer.parseInt(crtmodel.getValueAt(i,0).toString()) ==Integer.parseInt("unique_id")){
                          incart=1;
                          JOptionPane.showMessageDialog(null,"Medicine Already Exist In Cart");
                      }
                  }
              }
              if(incart == 0){
                  crtmodel.addRow(new Object[]{id,mname,cname,price,noofunit,amt});
                  totprice = totprice+Integer.parseInt(amt);
                  finalamtlabel.setText(String.valueOf(totprice));
                  //JOptionPane.showMessageDialog(null," medicine Added Successfully");   
              }
              clearmedfield();
              custmobilenobox.setText(mobileno);
              System.out.println(checkstock+id+mname+cname);
         }/*else{
             JOptionPane.showMessageDialog(null,"No . of Units and Medicine Id is required");   
         }*/        
    }//GEN-LAST:event_addcartbtnActionPerformed

    private void carttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carttableMouseClicked
        // TODO add your handling code here:
        int index = carttable.getSelectedRow();
        TableModel m = carttable.getModel();
        String mename= m.getValueAt(index,1).toString();
            int a = JOptionPane.showConfirmDialog(null,"Do you want to delete "+mename+" from cart","select",JOptionPane.YES_NO_OPTION);
            if(a==0){
                     //TableModel m = carttable.getModel();
                String tot= m.getValueAt(index,5).toString();
                totprice = totprice-Integer.parseInt(tot);
                finalamtlabel.setText(String.valueOf(totprice));
                ((DefaultTableModel) carttable.getModel()).removeRow(index);
                

                /*tp-=Float.parseFloat(tot);
                tpfield.setText(String.valueOf(tp));
                ((DefaultTableModel)carttable.getModel()).removeRow(i);*/ 
                
            }
    }//GEN-LAST:event_carttableMouseClicked

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        // TODO add your handling code here:
        if(totprice != 0 ){
            billid = getuniqueid("Bill-");
            DefaultTableModel crtmodel =(DefaultTableModel) carttable.getModel();
            if(crtmodel.getRowCount() != 0){
                for(int i =0 ;i<crtmodel.getRowCount();i++){
                    try{
                        Connection con = connectionprovider.getcon();
                        Statement st = con.createStatement();
                        String qty = String.valueOf(crtmodel.getValueAt(i,4));
                         String idd = String.valueOf(crtmodel.getValueAt(i,0));
                         System.out.println(idd);
                         int qtyi = Integer.parseInt(qty);
                          PreparedStatement ps = con.prepareStatement("update medicines  set quantity=quantity - ? where unique_id = ?");
                           ps.setInt(1, qtyi);
                           ps.setString(2, idd);
                           ps.executeUpdate();
                           /*ResultSet rs = st.executeQuery("select * from medicines where unique_id ='"+idd+"'");
                           while(rs.next()){
                           if(rs.getInt("quantity") <= minvalue){
                           System.out.println(rs.getInt("quantity"));
                           sendEmail("johnsaro1234@gmail.com",billid);
                           }else{
                               JOptionPane.showMessageDialog(null,"Medicine Out Of Stock "+rs.getInt("quantity")+"Left ");
                    }
                  }*/
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                    }
                }
            }
            try{
                SimpleDateFormat mf = new SimpleDateFormat("dd-MM-yyyy");
                Calendar ca = Calendar.getInstance();
                Connection con = connectionprovider.getcon();
                PreparedStatement ps = con.prepareStatement("insert into bill(billid_pk,billdate,totalpaid,customer_id) values(?,?,?,?)",Statement.RETURN_GENERATED_KEYS);
                ps.setString(1, billid);
                ps.setString(2, mf.format(ca.getTime()));
                ps.setString(3, String.valueOf(totprice));
                //ps.setString(4, un); 
                ps.setString(4,uid);
                ps.executeUpdate();
                Statement st = con.createStatement();
               /* ResultSet rs = ps.getGeneratedKeys();
                if (rs.next()) { 
                    billid = rs.getString(1); 
                } else {   
                    billid = null; 
                }
                 JOptionPane.showMessageDialog(null, "Generating Bill...");
                */
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            try{
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+billid+".pdf"));
            doc.open();
            Paragraph p = new Paragraph("                                                                JOHN SARO  MEDICALS\n");
            doc.add(p);
            Paragraph sep = new Paragraph("\n\n---------------------------------------------------------------------------------------------------------------------\n\n\n");
            doc.add(sep);
            Paragraph det = new Paragraph("\tBill ID : "+billid+"\nCustomer ID : "+uid+"\n Customer Name :"+custname+"\nDate : "+new Date());
            doc.add(det);
            PdfPTable tab = new PdfPTable(6);
            doc.add(sep);
            tab.addCell("Medicine ID");
            tab.addCell("Name");
            tab.addCell("Company Name");
            tab.addCell("Price/Unit");
            tab.addCell("Total Units"); 
            tab.addCell("Total Price");
            for(int i=0;i<carttable.getRowCount();i++){
                String  c1 = carttable.getValueAt(i,0).toString();
                String  c2 = carttable.getValueAt(i,1).toString();
                String  c3 = carttable.getValueAt(i,2).toString();
                String  c4 = carttable.getValueAt(i,3).toString();
                String  c5 = carttable.getValueAt(i,4).toString();
                String  c6 = carttable.getValueAt(i,5).toString();
                tab.addCell(c1);
                tab.addCell(c2);
                tab.addCell(c3);
                tab.addCell(c4);
                tab.addCell(c5);
                tab.addCell(c6);
                
            }
            doc.add(tab);
            
            Paragraph x = new Paragraph("\n\n\n\n\t\t\t\t      TOTAL AMOUNT : "+totprice);
            doc.add(x);
            Open.openById(String.valueOf(billid));
            System.out.println(billid);
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
            doc.close();
            //String recipientEmail,String billno
            sendEmail(custemail,billid);
            setVisible(false);
            new sellmedicine().setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Add Some Medicine Before Printing");
        }
        
    }//GEN-LAST:event_printbtnActionPerformed

    private void addcartbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addcartbtnMouseClicked
      
    }//GEN-LAST:event_addcartbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sellmedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sellmedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sellmedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sellmedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sellmedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcartbtn;
    private javax.swing.JTextField amtbox;
    private javax.swing.JButton backbtn;
    private javax.swing.JTable carttable;
    private javax.swing.JTextField companynamebox;
    private javax.swing.JTextField custmobilenobox;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel finalamtlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField medicinebox;
    private javax.swing.JTable medicinetable;
    private javax.swing.JTextField namebox;
    private javax.swing.JTextField no_of_units_box;
    private javax.swing.JButton printbtn;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField unitpricebox;
    // End of variables declaration//GEN-END:variables
}
