/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_management_system;

import dao.connectionprovider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Naveen
 */
public class updatecustomer extends javax.swing.JFrame {

    /**
     * Creates new form updatecustomer
     */
    private String emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
    private String mobileNumberPattern = "^[0-9]{10}$";
    public updatecustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backctn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mobilenobox = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressbox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailbox = new javax.swing.JTextField();
        updatebtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Update Customer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 70, 309, -1));

        backctn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        backctn.setText("Back");
        backctn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backctnActionPerformed(evt);
            }
        });
        getContentPane().add(backctn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1305, 31, -1, -1));

        exitbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1407, 31, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Mobile Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 275, 179, -1));

        mobilenobox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(mobilenobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 268, 255, -1));

        searchbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(964, 268, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 403, 153, -1));

        namebox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 442, 255, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 524, 160, -1));

        addressbox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(addressbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 609, 255, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("e-Mail");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 727, 141, -1));

        emailbox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(emailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 766, 255, -1));

        updatebtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/updateemp.png"))); // NOI18N
        updatebtn.setText("Update");
        updatebtn.setToolTipText("");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 573, 187, 82));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LIGHTBLUE.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backctnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backctnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new customercolumn().setVisible(true);
    }//GEN-LAST:event_backctnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"do you want to exit","select",JOptionPane.YES_NO_OPTION);
        if(a == 0 ){  //yes or no return yes =1 no=0
            System.exit(0);
        }    
    }//GEN-LAST:event_exitbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        int checkUserExist = 0;
        String mobileno = mobilenobox.getText();
        if(mobileno.equals("")){
            JOptionPane.showMessageDialog(null, "mobile number field required");
        } else{
            try{
                Connection con = connectionprovider.getcon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from customer where mobile_no ='"+mobileno+"'");
                while(rs.next()){
                    
                    checkUserExist = 1;
                    namebox.setText(rs.getString("name"));
                    mobilenobox.setText(rs.getString("mobile_no"));
                    emailbox.setText(rs.getString("email"));
                    addressbox.setText(rs.getString("address"));
                }
        }   catch(Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
            if(checkUserExist == 0){
                JOptionPane.showMessageDialog(null,"User does not exist");
            }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        String name = namebox.getText();
        String mobileNumber = mobilenobox.getText();
        String email = emailbox.getText();
        String address = addressbox.getText();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Name field is required.");
        } else if(mobileNumber.equals("")){
            JOptionPane.showMessageDialog(null,"Mobile Number field is required.");
        } else if(!mobileNumber.matches(mobileNumberPattern) || mobileNumber.length() !=10){
            JOptionPane.showMessageDialog(null,"Mobile Number field is invalid.");
        } else if(!email.matches(emailPattern)){
            JOptionPane.showMessageDialog(null,"Email field is invalid.");
        } else if(email.equals("")){
            JOptionPane.showMessageDialog(null,"Email field is required.");
        } else if(address.equals("")){
            JOptionPane.showMessageDialog(null,"Address field is required");
        } else{
            try {
                            Connection con = connectionprovider.getcon();
                            PreparedStatement ps = con.prepareStatement("UPDATE customer SET  name=?, mobile_no=?, email=?, address=? WHERE mobile_no='"+mobileNumber+"'");
                            ps.setString(1, name);
                            ps.setString(2,mobileNumber);
                            ps.setString(3, email);
                            ps.setString(4,address);
                            int rowsAffected = ps.executeUpdate(); 
                            if (rowsAffected > 0) {
                                JOptionPane.showMessageDialog(null, "User Updated Successfully");
                                setVisible(false);
                                new updatecustomer().setVisible(true);
                            } else {
                                JOptionPane.showMessageDialog(null, "Update failed. No matching user found.");
                            }
            }catch(Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatecustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatecustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatecustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatecustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatecustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressbox;
    private javax.swing.JButton backctn;
    private javax.swing.JTextField emailbox;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mobilenobox;
    private javax.swing.JTextField namebox;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
