/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_management_system;
import java.text.SimpleDateFormat;
import java.sql.*;
//import java.time.*;
import dao.connectionprovider;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author Naveen
 */
public class updateemployee extends javax.swing.JFrame {
    private String emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
    private String mobileNumberPattern = "^[0-9]{10}$";
    

    /**
     * Creates new form updateemployee
     */
    public updateemployee() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernamebox = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        userrolebox = new javax.swing.JComboBox<>();
        backbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mobilenobox = new javax.swing.JTextField();
        updatebtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        emailbox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addressbox = new javax.swing.JTextField();
        datebox = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Update Employee Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 69, 287, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("User Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 154, 110, -1));

        usernamebox.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        getContentPane().add(usernamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 154, 299, -1));

        searchbtn.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        searchbtn.setText("search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1014, 152, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("User Role");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 251, 114, -1));

        userrolebox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        userrolebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Pharmacist", " " }));
        getContentPane().add(userrolebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 290, 299, -1));

        backbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 40, -1, -1));

        exitbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 154, -1));

        namebox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(namebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 299, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("DOB Date f Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, 250, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("Mobile No");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 410, 299, -1));

        mobilenobox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(mobilenobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 450, 299, -1));

        updatebtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/updateemp.png"))); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 717, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("e-Mail");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 251, 168, -1));

        emailbox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        emailbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailboxActionPerformed(evt);
            }
        });
        getContentPane().add(emailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 290, 299, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel10.setText("Address");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 242, -1));

        addressbox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        addressbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressboxActionPerformed(evt);
            }
        });
        getContentPane().add(addressbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 307, -1));
        getContentPane().add(datebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 600, 300, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1111.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailboxActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new OwnerDashboard().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"do you want to exit","select",JOptionPane.YES_NO_OPTION);
        if(a == 0 ){  //yes or no return yes =1 no=0
            System.exit(0);
        }     
    }//GEN-LAST:event_exitbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        int checkUserExist = 0;
        String username = usernamebox.getText();
        if(username.equals("")){
            JOptionPane.showMessageDialog(null, "Username field is required");
        } else{
            SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
            try{
                Connection con = connectionprovider.getcon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from app_user where user_name = '"+username+"'");
                while(rs.next()){
                    usernamebox.setEditable(false);
                    checkUserExist = 1;
                    namebox.setText(rs.getString("name"));
                    mobilenobox.setText(rs.getString("mobile_no"));
                    emailbox.setText(rs.getString("email"));
                    addressbox.setText(rs.getString("address"));
                    String dob = rs.getString("dob");
                    if(dob!= ""){
                        try{
                           datebox.setDate(dFormat.parse(dob));
                        }
                        catch(Exception e){ }
                    }
                    if(rs.getString("userRole").equals("Admin")) {
                        userrolebox.removeAllItems();
                        userrolebox.addItem("Admin");
                        userrolebox.addItem("Pharmacist");
                    }
                    else{
                        userrolebox.removeAllItems();                        
                        userrolebox.addItem("Pharmacist");
                        userrolebox.addItem("Admin");
                    }
                }
        }   catch(Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
            if(checkUserExist == 0){
                JOptionPane.showMessageDialog(null,"Username does not exist");
            }
        }

    }//GEN-LAST:event_searchbtnActionPerformed

    private void addressboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressboxActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        String userRole = (String) userrolebox.getSelectedItem();
        String name = namebox.getText();
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = datebox.getDate();
        String dob ="";
        if(date != null){
            dob = dFormat.format(datebox.getDate());
        }
        String mobileNumber = mobilenobox.getText();
        String email = emailbox.getText();
        String username = usernamebox.getText();
        String address = addressbox.getText();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Name field is required.");
        } else if(dob.equals("")){
            JOptionPane.showMessageDialog(null,"Date of Birth field is required.");
        } else if(mobileNumber.equals("")){
            JOptionPane.showMessageDialog(null,"Mobile Number field is required.");
        } else if(!mobileNumber.matches(mobileNumberPattern) || mobileNumber.length() !=10){
            JOptionPane.showMessageDialog(null,"Mobile Number field is invalid.");
        } else if(!email.matches(emailPattern)){
            JOptionPane.showMessageDialog(null,"Email field is invalid.");
        } else if(email.equals("")){
            JOptionPane.showMessageDialog(null,"Email field is required.");
        } else if(username.equals("")){
            JOptionPane.showMessageDialog(null,"Username field is required.");
        } else if(address.equals("")){
            JOptionPane.showMessageDialog(null,"Address field is required");
        } else{
            try {
                            Connection con = connectionprovider.getcon();
                            PreparedStatement ps = con.prepareStatement("UPDATE app_user SET userRole=?, name=?, dob=?, mobile_no=?, email=?, address=? WHERE user_name=?");
    ps.setString(1, userRole);
    ps.setString(2, name);
    ps.setString(3, dob);
    ps.setString(4, mobileNumber);
    ps.setString(5, email);
    ps.setString(6, address);
    ps.setString(7, username);
    int rowsAffected = ps.executeUpdate(); 
    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(null, "User Updated Successfully");
        setVisible(false);
        new updateemployee().setVisible(true);
    } else {
        JOptionPane.showMessageDialog(null, "Update failed. No matching user found.");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}

        }

    }//GEN-LAST:event_updatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressbox;
    private javax.swing.JButton backbtn;
    private com.toedter.calendar.JDateChooser datebox;
    private javax.swing.JTextField emailbox;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mobilenobox;
    private javax.swing.JTextField namebox;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField usernamebox;
    private javax.swing.JComboBox<String> userrolebox;
    // End of variables declaration//GEN-END:variables
}
