/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_management_system;
import java.sql.*;
import dao.connectionprovider;
import javax.swing.JOptionPane;

/**
 *
 * @author Naveen
 */
public class updatemedicine extends javax.swing.JFrame {
    private String mobileNumberPattern = "^[0-9]{10}$";

    /**
     * Creates new form updatemedicine
     */
    public updatemedicine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mednamebox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comnamebox = new javax.swing.JTextField();
        unitpricebox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totquantbox = new javax.swing.JTextField();
        updatebtn = new javax.swing.JButton();
        medidbox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addquantbox = new javax.swing.JTextField();
        backbtn2 = new javax.swing.JButton();
        exitbtn2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Update Medicine");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 62, 294, -1));

        backbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        backbtn.setText("Back");
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(2085, 62, -1, -1));

        exitbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        exitbtn.setText("Exit");
        getContentPane().add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(2178, 62, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Medicine ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 185, 181, -1));

        searchbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1091, 177, -1, 37));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Medicine Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 250, -1));

        mednamebox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(mednamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 250, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Company Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 250, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("Unit Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 280, 250, -1));

        comnamebox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(comnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 250, -1));

        unitpricebox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        unitpricebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitpriceboxActionPerformed(evt);
            }
        });
        getContentPane().add(unitpricebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 320, 250, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setText("Total Quantity");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 400, 250, -1));

        totquantbox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        totquantbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totquantboxActionPerformed(evt);
            }
        });
        getContentPane().add(totquantbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 440, 250, -1));

        updatebtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addmed.jpg"))); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 640, -1, -1));

        medidbox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(medidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 182, 408, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Add Quantity");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, -1, -1));

        addquantbox.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        addquantbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addquantboxActionPerformed(evt);
            }
        });
        getContentPane().add(addquantbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 80, 40));

        backbtn2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        backbtn2.setText("Back");
        backbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 40, -1, -1));

        exitbtn2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        exitbtn2.setText("Exit");
        exitbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 40, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ORANGE_TABLET.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        int checkExist = 0;
        String medid = medidbox.getText();
        if(medid.equals("")){
            JOptionPane.showMessageDialog(null, "medicine ID field is required");
        } else{
            try{
                Connection con = connectionprovider.getcon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from medicines where unique_id = '"+medid+"'");
                while(rs.next()){
                    medidbox.setEditable(false);
                    checkExist = 1;
                    mednamebox.setText(rs.getString("medname"));
                    comnamebox.setText(rs.getString("companyname"));
                    unitpricebox.setText(rs.getString("amount"));
                    totquantbox.setText(rs.getString("quantity"));
                    addquantbox.setText("0");
                }
                if(checkExist ==0){
                    JOptionPane.showMessageDialog(null, "medicine doesn't exist");
                    
                }
            }
            catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void totquantboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totquantboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totquantboxActionPerformed

    private void addquantboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addquantboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addquantboxActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
                    String medname = mednamebox.getText();
                    String comname = comnamebox.getText();
                    String unit = unitpricebox.getText();
                    String totqua = totquantbox.getText();
                    String add = addquantbox.getText();
                    String medid = medidbox.getText();
                    int newstock = 0;
                    if(mednamebox.equals("")){
            JOptionPane.showMessageDialog(null,"Medicine Name field is required.");
        } else if(comnamebox.equals("")){
            JOptionPane.showMessageDialog(null,"Company Name field is required.");
        } else if(unitpricebox.equals("")){
            JOptionPane.showMessageDialog(null,"unitprice field is required.");
        } else if(totquantbox.equals("")){
            JOptionPane.showMessageDialog(null,"Total Quantity field is invalid.");
        }else if(addquantbox.equals("")){
            JOptionPane.showMessageDialog(null,"add quantity  field is required.");
        }else{
            try {
                newstock = Integer.parseInt(add) + Integer.parseInt(totqua);
                Connection con = connectionprovider.getcon();
                PreparedStatement ps = con.prepareStatement("UPDATE medicines SET medname=?, companyname=?, quantity = ? ,amount=? WHERE unique_id=?");
                ps.setString(1, medname);
                ps.setString(2, comname);
                ps.setInt(3, newstock);
                ps.setString(4, unit);
                ps.setString(5, medid);
                int rowsAffected = ps.executeUpdate(); 
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "Medicine Details Updated Successfully");
                    setVisible(false);
                    new updatemedicine().setVisible(true);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Update failed. No matching medicine found.");
                }
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void exitbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtn2ActionPerformed
        // TODO add your handling code here:
         int a = JOptionPane.showConfirmDialog(null,"do you want to exit","select",JOptionPane.YES_NO_OPTION);
        if(a == 0 ){
            System.exit(0);
        }
    }//GEN-LAST:event_exitbtn2ActionPerformed

    private void unitpriceboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitpriceboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitpriceboxActionPerformed

    private void backbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new medicines().setVisible(true);
    }//GEN-LAST:event_backbtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatemedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatemedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatemedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatemedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatemedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addquantbox;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton backbtn2;
    private javax.swing.JTextField comnamebox;
    private javax.swing.JButton exitbtn;
    private javax.swing.JButton exitbtn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField medidbox;
    private javax.swing.JTextField mednamebox;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField totquantbox;
    private javax.swing.JTextField unitpricebox;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
