/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy_management_system;

import javax.swing.JOptionPane;

/**
 *
 * @author Naveen
 */
public class workerboard extends javax.swing.JFrame {
     public String uname = "";
     public String role = "worker";

    /**
     * Creates new form workerboard
     */
    public workerboard() {
        initComponents();
    }
    public workerboard(String username) {
        uname = username;
        initComponents();
                System.out.println("uname");

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        profilebtn = new javax.swing.JButton();
        medicinebtn = new javax.swing.JButton();
        viewbillbtn = new javax.swing.JButton();
        customerbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("PHARMACIST DASHBOARD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 503, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 60, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 60, -1, -1));

        profilebtn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        profilebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/id.png"))); // NOI18N
        profilebtn.setText("PROFILE");
        profilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebtnActionPerformed(evt);
            }
        });
        getContentPane().add(profilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 580, 207, -1));

        medicinebtn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        medicinebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medicine 2.png"))); // NOI18N
        medicinebtn.setText("MEDICINE");
        medicinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicinebtnActionPerformed(evt);
            }
        });
        getContentPane().add(medicinebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        viewbillbtn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        viewbillbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1bill.png"))); // NOI18N
        viewbillbtn.setText("VIEW BILL");
        viewbillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbillbtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewbillbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, -1, -1));

        customerbtn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        customerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Users.png"))); // NOI18N
        customerbtn.setText("CUSTOMER");
        customerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerbtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/DASHBOARD BACKGROUND_1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"do you want to exit","select",JOptionPane.YES_NO_OPTION);
        if(a == 0 ){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void medicinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicinebtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new medicines(role,uname).setVisible(true);
    }//GEN-LAST:event_medicinebtnActionPerformed

    private void customerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("aaaa");
        new customercolumn(role).setVisible(true);
    }//GEN-LAST:event_customerbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"do yo want to logout application","select",JOptionPane.YES_NO_OPTION);
        if(a == 0 ){
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void profilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebtnActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        System.out.println("qwerty");
        //new profile().setVisible(true);
        new profile(uname,role).setVisible(true);
        System.out.println("from worker profile"+uname+role);
    }//GEN-LAST:event_profilebtnActionPerformed

    private void viewbillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbillbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        System.out.println("qwerty");
        new viewbill(role).setVisible(true);
    }//GEN-LAST:event_viewbillbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(workerboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(workerboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(workerboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(workerboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new workerboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton medicinebtn;
    private javax.swing.JButton profilebtn;
    private javax.swing.JButton viewbillbtn;
    // End of variables declaration//GEN-END:variables
}
